repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        name: Check for merge conflict strings

      - id: end-of-file-fixer
        name: Fix missing newline at the end of files

      - id: check-shebang-scripts-are-executable
        name: Check shell scripts are executable
        files: \.(sh)$

      - id: check-yaml
        name: Check pipelines configuration
        files: ^(.github)

  - repo: https://github.com/pycqa/flake8
    rev: "7ef0350a439c93166bc8ba89fcc3de6a9a664e6c" # release 6.1.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: git-secrets
        name: Git Secrets
        description: git-secrets scans commits, commit messages, and --no-ff merges to prevent adding secrets into your git repositories.
        entry: bash
        args:
          - -c
          - 'docker run -v "$LOCAL_WORKSPACE_FOLDER:/src" git-secrets --pre_commit_hook'
        language: system
fail_fast: true
default_stages: [commit]
