server:
  port: 9001
  tomcat:
    threads:
      max: 10

management:
  endpoints:
    web.exposure:
      include: "*"

###Remote terminology validation:

##Example without auth:
#terminology:
#  url: https://r4.ontoserver.csiro.au/fhir

##Example with auth:
#terminology:
#  url: https://ontology.nhs.uk/authoring/fhir/
#  authorization:
#    tokenUrl: https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token
#    clientId: test
#    clientSecret: test
