name: merge to main workflow

on:
  push:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@dac60c1e29babc62013e7bb9ade002cb381c4c49
    with:
      verify_published_from_main_image: true

  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@383f3f9eaf3cb553ebcd74897bfed4d5e387629e
    needs: [get_config_values]
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      run_docker_scan: true
      docker_images: validator

  build:
    name: build
    runs-on: ubuntu-22.04
    container:
      image: ${{ needs.get_config_values.outputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    needs: [get_config_values]
    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0 # This causes all history to be fetched, which is required for calculate-version to function
      - name: Install python packages
        run: poetry install

      - name: Run tests, and build
        run: make build

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        name: upload build artifact
        with:
          name: packaged_code
          path: |
            fhir-validator.jar

  package_code:
    needs: [quality_checks, build, get_config_values]
    runs-on: ubuntu-22.04
    container:
      image: ${{ needs.get_config_values.outputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash

    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0 # This causes all history to be fetched, which is required for calculate-version to function

      - name: download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: packaged_code
          path: .

      - name: Install python packages
        run: poetry install

      - name: Set SPEC_VERSION env var
        # calculate new version number
        # and update Dockerfile with version and commit sha so its available in docker image when it is built by fhir facade
        run: |
          VALIDATOR_VERSION=$(poetry run python scripts/calculate_version.py)
          COMMIT_SHA=${{ github.sha }}
          sed -i 's/^ARG VALIDATOR_VERSION=.*/ARG VALIDATOR_VERSION='"$VALIDATOR_VERSION"'/; s/^ARG COMMIT_SHA=.*/ARG COMMIT_SHA='"$COMMIT_SHA"'/' Dockerfile
          echo "VALIDATOR_VERSION=${VALIDATOR_VERSION}" >> "$GITHUB_ENV"

      - name: Create release
        id: create_release
        # using commit hash for version v1.16.0
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.VALIDATOR_VERSION }}
          commit: ${{  github.sha }}
          artifacts: "fhir-validator.jar,Dockerfile,src/main/resources/manifest.json"
          makeLatest: true
          body: |
            ## Commit message
            ${{ github.event.head_commit.message }}
            ## Info
            [See code diff](${{ github.event.compare }})
            [Release workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            It was initialized by [${{ github.event.sender.login }}](${{ github.event.sender.html_url }})
