name: Pull request test and build
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@e798d5aee897de6f7dc387dd5623fcd9ba4c8929
    permissions:
      attestations: read
      contents: read
      packages: read
    with:
      verify_published_from_main_image: false
  quality_checks:
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@8399c1f015c1304e40771cbd8ccc24c7ed48fdbc
    needs: [get_config_values]
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
      run_docker_scan: true
      docker_images: validator
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  pr_title_format_check:
    uses: NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@bda627e2ce1a32ea56bcc815aec57b06cfa63c9d
    permissions:
      pull-requests: write
